### ISSUE TITLE
Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"

### ISSUE THREAD

**Issue by mikebourbeauart** [steveliles/nextjs-nested-layouts#2]
I'm trying to run `npm install`, but I keep getting this error in the title. 

I've seen some suggestions involving paths defined in the .npmrc file. I don't really want to mess with anything because I don't know if it will impact my other projects.

What should I do about this? Thanks!

**Comment by mikebourbeauart** [comment]
Finally figured it out. There's a `yarn.lock` in the repo. Deleting it fixed the problem. 

Should this be removed from the repo and added to `.gitignore`? Same thing with `package-lock.json`?

**Comment by steveliles** [comment]
Whoops, yeah looks like I had the wrong npmrc profile enabled when I set up the repo, I'll switch that over to default npm, thanks for letting me know.

**Comment by abdalhafezsayeh** [comment]
Is a new repo provided ?

**Comment by steveliles** [comment]
apologies, looks like i forgot to remove the old yarn lock ... i've done that now (replaced with a correct package-lock).

**Comment by abdalhafezsayeh** [comment]
thank you steve
